### ISSUE TITLE
Is it an error?

### ISSUE THREAD

**Issue by chaochaoSZ** [manishpatel005/tinysearch#2]
I read the code in gui_v4.py， I find that you don't use the model that you train.
What you do is only built a GUI and use bert-as-service to get the embedding and calculate the cosine similarity.
Why don't you use the method you provide?

**Comment by chaochaoSZ** [comment]
Just curious why this git appear in the first page when I search Bert semantic search.
I also read the paper and the code, find mybe the code is not complete but the paper said it can get very interesting results.

**Comment by manishpatel005** [comment]
Hi 
Thanks for the comment. I saw that I have commented out the portion of the code where self.model.predict is being used. You can uncomment it and comment out the cosine similarity one. I guess I uploaded the code after I made the comparison with Cosine and forgot to comment it out while uploading.
